// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vjqhpuflbvmaillsgswm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZqcWhwdWZsYnZtYWlsbHNnc3dtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5Nzc1MDAsImV4cCI6MjA2MDU1MzUwMH0.zj7duoGiEhAY4dDXWGsCsmL3L77l8GVVhCgOrvCsL4s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);